Web/Controllers/PublicacionController.cs
using LogicaNegocio;
using Microsoft.AspNetCore.Mvc;

namespace Web.Controllers
{
    public class PublicacionController : Controller
    {
        private Sistema sistema = Sistema.Instancia;

        public IActionResult Index()
        {
            if (HttpContext.Session.GetString("usuario-tipo") == "Administrador")
            {
                return RedirectToAction("Index", "Usuario");
            }
            else if(HttpContext.Session.GetString("usuario-tipo") == "Cliente")
            {
                return View(sistema.Publicaciones);
            }
            return RedirectToAction("Login", "Home");
        }
    }
}

Web/Views/Shared/_Layout.cshtml
@using LogicaNegocio
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                @if (Context.Session.GetString("usuario-tipo") == null) {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                } else if (Context.Session.GetString("usuario-tipo") == "Administrador") {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mi perfil</a>
                } else if (Context.Session.GetString("usuario-tipo") == "Cliente") {
                    <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Mi perfil</a>
                }
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @if (Context.Session.GetString("usuario-tipo") == null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Login">Iniciar sesión</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Cliente" asp-action="Create">Registrarse</a>
                            </li>
                        }
                        else if (Context.Session.GetString("usuario-tipo") == "Administrador")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Subasta" asp-action="Index">Ver subastas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                        else if (Context.Session.GetString("usuario-tipo") == "Cliente")
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Publicacion" asp-action="Index">Ver publicaciones</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Logout">Cerrar sesión</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>